## ---- data source
task_name: ''
given_path: null
given_dir: null
cases: null
parallel: false
skip_if_processed_recently: false
check_time: 1674417578

## ---- control
preview_scene: false
step_by_step: false
use_gym: false
auto_play: true
verbose: false
time_step: 0.005

## ---- visual
width: 1440
height: 1120
fx: 600
camera_point: null # [8.5, 2.5, 3]
target_point: null # [0, 2.5, 0]
camera_kwargs: null
camera_movement: null
light_conf: null

## ---- purposes
check_collisions: false
cfree_range: 0.1
visualize_collisions: false
evaluate_quality: false

## ---- outputs
save_jpg: false
save_composed_jpg: false
save_gif: false
save_animation_json: false
save_mp4: true
mp4_side_view: false
mp4_top_view: false