## ---- data source
task_name: ''
#given_path: '/home/zhutiany/Documents/vlm-tamp/experiments/kitchen/240218_125039_default'
given_path: '/home/zhutiany/Documents/vlm-tamp/experiments/test_kitchen_chicken_soup/240220_210718_default'
#given_path: '/home/zhutiany/Documents/vlm-tamp/experiments/kitchen_gpt/240212_110836_vlm-tamp_object-related'
given_dir: none
cases: none
parallel: false
skip_if_processed_recently: false
check_time: 1674417578

## ---- control
preview_scene: false
step_by_step: true
use_gym: false
auto_play: true
verbose: false

## ---- visual
width: 1440
height: 1120
fx: 600
camera_point: (8.5, 2.5, 3)
target_point: (0, 2.5, 0))
camera_kwargs: none
camera_movement: none
light_conf: none

## ---- purposes
check_collisions: false
cfree_range: 0.1
visualize_collisions: false
evaluate_quality: false

## ---- outputs
save_jpg: false
save_composed_jpg: false
save_gif: false
save_animation_json: false
save_mp4: false
mp4_side_view: false
mp4_top_view: false